field.value.condition_field:
  type: mapping
  label: 'Default value'
  mapping:
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Visibility Condition'

field.field_settings.condition_field:
  type: mapping
  label: 'Condition field settings'
