# Schema for the configuration files of the Mailjet module.

mailjet.settings:
  type: config_object
  label: 'Mailjet Settings'
  mapping:
    mailjet_username:
      type: string
      label: 'Mailjet username'
    mailjet_password:
      type: string
      label: 'Mailjet password'
    mailjet_mail:
      type: boolean
      label: 'Mailjet email status'
    mailjet_active:
      type: boolean
      label: 'Mailjet active status'
    mail_headers_allow_html_mailjet:
      type: boolean
      label: 'Allow html mailjet'
    apitoken:
      type: string
      label: 'Api token'
    mailjet_title:
      type: string
      label: 'Mailjet title'
      translatable: true

