<?php

/**
 * @file
 * Contains kidiklik_front.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function kidiklik_front_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kidiklik_front module.
    case 'help.page.kidiklik_front':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module pour la gestion du front') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function kidiklik_front_theme() {
  return [
    'kidiklik_front' => [
      'render element' => 'children',
    ],
  ];
}




function kidiklik_front_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	if($form_id=="webform_submission_contact_add_form") {
		
	}
	
	if($form_id=="contact_message_pour_joindre_kidiklik_form" ) {

		$form["#validate"][]="kidiklik_front_validate_contact_form";

	}
	
	if($form_id=="node_message_contact_form") {
		$term_dep=get_term_departement();
		$form["#validate"][]="kidiklik_front_validate_contact_form";
		$form["#attached"]["library"][]="kidiklik_front/kidiklik_front.actions";
		$form["field_departement"]["widget"][0]["target_id"]["#default_value"]=taxonomy_term_load($term_dep);
		//unset($form["field_date_envoi"]);
		//kint($form);
		//$form["#redirect"]="contact.html";
		
	}
}

function kidiklik_front_validate_contact_form($form, FormStateInterface $form_state) {
	/*$entity = \Drupal::entityManager()->getStorage('contact_form')->load("pour_joindre_kidiklik");
	$entity->set("recipients","toto@tot.fr");*/
	
	//kint($form_state);exit;
	

	//kint($entity);exit;
}



/*
 * Modification de la requête sql d'une vue
 */
function kidiklik_front_views_query_alter(Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\QueryPluginBase $query) {
	$term_dep=get_term_departement();
	
	if($view->current_display=="diaporama") {
		/* la date de début du bloc de mise en avant doit être inférieur ou égal à la date du jour */ 
		$query->where[1]["conditions"][2]["value"]=date("Y-m-d");
		$query->where[1]["conditions"][2]["operator"]="<=";
		/* la date de fin du bloc de mise en avant doit être supérieur ou égal à la date du jour */
		$query->where[1]["conditions"][3]["value"]=date("Y-m-d");
		$query->where[1]["conditions"][3]["operator"]=">=";
		//kint($query->where);
		
	}
	
	if($view->current_display=="recherche_activites") {

	}

}


