<?php

/**
 * Implements hook_theme().
 */
function kidiklik_front_publicite_theme() {
  return [
    'publicite_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}



/*
 * Modification de la requête sql d'une vue
 */
function kidiklik_front_publicite_views_query_alter(Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\QueryPluginBase $query) {
	$term_dep=get_term_departement();

	if($view->getTitle()=="Blocs publicités") {
		/* recherche des publicite */
		/* date début */
		//$query->where[1]["conditions"][2]["field"]="DATE_FORMAT(node__field_date_debut.field_date_debut_value, '%Y-%m-%d') <= DATE_FORMAT('".date("Y-m-d")."', '%Y-%m-%d')";
		/* date fin */
		//$query->where[1]["conditions"][3]["field"]="DATE_FORMAT(node__field_date_fin.field_date_fin_value, '%Y-%m-%d') >= DATE_FORMAT('".date("Y-m-d")."', '%Y-%m-%d')";
		$query->where[1]["conditions"][2]["field"]="DATE_FORMAT(paragraphs_item_field_data_node__field_date__paragraph__field_date_de_debut.field_date_de_debut_value, '%Y-%m-%d') <= DATE_FORMAT('".date("Y-m-d")."', '%Y-%m-%d')";
		/* date fin */
		$query->where[1]["conditions"][3]["field"]="DATE_FORMAT(paragraphs_item_field_data_node__field_date__paragraph__field_date_de_fin.field_date_de_fin_value, '%Y-%m-%d') >= DATE_FORMAT('".date("Y-m-d")."', '%Y-%m-%d')";
		
		/* 1er condition : la publicité fait partie du département */
		$query->where[2]["conditions"][0]["value"]=$term_dep;
		$query->where[2]["conditions"][0]["operator"]="=";
		/* 2eme condition : la publicité est pour tous les sites */
		/* rien à faire */
		/* 3eme conditions : la publicite est partagée avec le dép */
		$query->where[2]["conditions"][2]["value"]=$term_dep;
		$query->where[2]["conditions"][2]["operator"]="=";

	}

	
}
