<?php

/**
 * @file
 * Contains kidiklik_admin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\ReplaceCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_help().
 */
function kidiklik_admin_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kidiklik_admin module.
    case 'help.page.kidiklik_admin':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fonctionnalités admin kidiklik') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function kidiklik_admin_theme() {
  return [
    'kidiklik_admin' => [
      'render element' => 'children',
    ],
  ];
}




/**
 * modification de formulaire
 */
function kidiklik_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
	$term_dep=get_term_departement();
	
	
	if($form_id=="node_publicite_form" || $form_id=="node_publicite_edit_form") {
		$form["#redirect"]="admin/publicites";
		$form["field_adherent"]["widget"]["#multiple"]=FALSE;
		$adherents=\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"adherent","field_departement"=>$term_dep]);
		$tab=[];
		$tab[""]="Veuillez choisir un client";
		foreach($adherents as $key=>$adherent) {
			$tab[$key]=$adherent->getTitle();
		}
		$form["field_adherent"]["widget"]["#options"]=$tab;

		foreach($form['field_partage_departements']['widget']['#options'] as $key=>$item)
			if(!(int)$item->__toString()) unset($form['field_partage_departements']['widget']['#options'][$key]);
			else {
				$nom_departement=\Drupal::entityTypeManager()->getStorage("taxonomy_term")->load($key);
				$form['field_partage_departements']['widget']['#options'][$key]=current($nom_departement->get("field_nom")->getValue())["value"]." (".$nom_departement->getName().")";;
//				kint($nom_departement->get("field_nom")->getValue());

			}
			//kint($item->__toString());

	//kint($form['field_partage_departements']);	
	}
	
	
	if($form_id=="taxonomy_term_rubriques_activite_form") {
		/* on récupére le paramètre url destination */
		$arg=\Drupal::request()->query->get("destination");
		/* puis l'id de la catégorie mère */
		$tab=explode("/",$arg);
		$cat_mere=\Drupal::entityTypeManager()->getStorage("taxonomy_term")->load($tab[3]);
		if(!empty($cat_mere)) 
			$form["cat_mere"]=[
				"#type"=>"html_tag",
				"#tag" => "H1",
				"#value" => "Rubrique ".$cat_mere->getName(),
				"#weight" => 0,
			];

		$form["field_departement"]["widget"][0]["target_id"]["#default_value"]=taxonomy_term_load($term_dep);
		/* on va lister uniquement les catégorie mère */
		$tmp=\Drupal::entityTypeManager()->getStorage("taxonomy_term")->loadByProperties(["vid"=>"rubriques_activite"]);
		$liste=[];
		foreach($tmp as $key=>$item) {
			if(!current($item->parent->getValue()[0])) {
				$liste[$key]=$item->getName();

			}
		}
		//$form["relations"]["parent"]["#multiple"]=FALSE;
		$form["relations"]["parent"]["#options"]=$liste;
		$form["relations"]["parent"]["#default_value"]=$tab[3];


		//kint($form);

	}

	if($form_id=="node_bloc_de_mise_en_avant_edit_form" || $form_id=="node_bloc_de_mise_en_avant_form") {
		$form["field_adherent"]["widget"]["#multiple"]=FALSE;
		
		$adherents=\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"adherent","field_departement"=>$term_dep]);
		$tab[""]="Veuillez choisir un adhérent";
		foreach($adherents as $key=>$adherent) {
			$tab[$key]=$adherent->getTitle();
		}
		$form["field_adherent"]["widget"]["#options"]=$tab;
	}
	
	if($form_id=="node_agenda_edit_form" || $form_id=="node_agenda_form") {
		$adherents=\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"adherent","field_departement"=>$term_dep]);
		
		$tab=[];
		$tab[""]="Veuillez choisir un client";
		//$form["field_ville"]["widget"]["#options"]=$tab;
		if($form["field_ville"]["widget"]["#default_value"]) {
				foreach($form["field_ville"]["widget"]["#options"] as $key=>&$item) {
					
					
					if($key!=(int)current($form["field_ville"]["widget"]["#default_value"])) unset($form["field_ville"]["widget"]["#options"][$key]);
				}
				
		}else $form["field_ville"]["widget"]["#options"]=$tab;
		
		//$form["save_activite"]=$form["field_activite"]["widget"]["#options"];
		$tab[""]="Veuillez choisir une activité";
		$form["field_activite"]["widget"]["#options"]=$tab;
		$form["field_activite"]["widget"]["#needs_validation"]=false;
		$form["field_activite"]["widget"]["#limit_validation_errors"]=[];
		$form["field_activite"]["#limit_validation_errors"]=[];
		//	kint($form["field_ville"]["widget"]);
		foreach($adherents as $key=>$adherent) {
			$tab[$key]=$adherent->getTitle();
		}
		$form["field_adherent"]["widget"]["#options"]=$tab;
		
		/* le champ est configuré par défaut en multiple valeur, on bloque à une simple valeur */
		$form["field_adherent"]["widget"]["#multiple"]=FALSE;
		$form["field_adherent"]["widget"]["#ajax"]=[
			"callback"=>"getAjaxCoordonnees",
			"disable-refocus" => FALSE,
			"event" => "change",
			"wrapper" =>"coordonnees-adherent",
			"progress"=>[
				"type"=>"throbber",
				"message"=>"Analyse",
			],

		];
		
		
		$form["#attached"]["library"][]="kidiklik_admin/kidiklik_admin.commands";
		$form["#submit"][]="kidiklik_admin_form_submit";
		$form["#validate"][]="kidiklik_admin_form_validate";
		//kint($form);

	}
	
	if($form_id=="node_article_edit_form" || $form_id=="node_article_form" || $form_id=="node_reportage_edit_form" || $form_id=="node_reportage_form") {
		$adherents=\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"adherent","field_departement"=>$term_dep]);
		$tab=[];
		$tab[""]="Veuillez choisir un client";
		foreach($adherents as $key=>$adherent) {
			$tab[$key]=$adherent->getTitle();
		}
		$form["field_adherent"]["widget"]["#options"]=$tab;
		
		/* le champ est configuré par défaut en multiple valeur, on bloque à une simple valeur */
		$form["field_adherent"]["widget"]["#multiple"]=FALSE;
	}
	
	
	/* on reformate le choix des activités pour ne choisir que des enfants */
	if($form_id=="node_activite_edit_form" || $form_id=="node_activite_form") {
		$form["#attached"]["library"][]="kidiklik_admin/kidiklik_admin.commands";
		//kint($form);
		/* le champ est configuré par défaut en multiple valeur, on bloque à une simple valeur */
		$form["field_adherent"]["widget"]["#multiple"]=FALSE;
		$form["field_adherent"]["widget"]["#ajax"]=[
			"callback"=>"getAjaxCoordonnees",
			"disable-refocus" => FALSE,
			"event" => "change",
			"wrapper" =>"coordonnees-adherent",
			"progress"=>[
				"type"=>"throbber",
				"message"=>"Analyse",
			],

		];
//kint($form);
		/* formattage de la balise select avec affichage par catégorie */
		if(\Drupal::currentUser()->id()!=1) {
			$rub=$form["field_rubriques_activite"]["widget"]["#options"];
			$tab=[];
			$n="";
			foreach($rub as $k=>$r) {
				if($k!="_none") {
					$t=taxonomy_term_load($k);
					$p=current($t->parent->getValue()[0]);
					if(!(int)$p) {
						$n=current($t->name->getValue()[0]);
					} else {
						if(current($t->get("field_departement")->getValue())["target_id"]==$term_dep)
							$tab[$n][$k]=current($t->name->getValue()[0]);
					}
				}
			}
			$form["field_rubriques_activite"]["widget"]["#options"]=$tab;
		
			$form["field_rubriques_activite"]["widget"]["#size"]=1;
			$form["#redirect"]="admin/activites";
			
			$adherents=\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"adherent","field_departement"=>$term_dep]);
			$tab=[];
			$tab[""]="Veuillez choisir un client";
			foreach($adherents as $key=>$adherent) {
				$tab[$key]=$adherent->getTitle();
			}
			$form["field_adherent"]["widget"]["#options"]=$tab;
			
			if($form["field_ville"]["widget"]["#default_value"]) {
				foreach($form["field_ville"]["widget"]["#options"] as $key=>&$item) {
					
					
					if($key!=(int)current($form["field_ville"]["widget"]["#default_value"])) unset($form["field_ville"]["widget"]["#options"][$key]);
				}
				
			}/*else $form["field_ville"]["widget"]["#options"]=[];*/
		}
	}
	
	
	
	if($form_id=="node_adherent_edit_form" || $form_id=="node_adherent_form") {
		$form["#attached"]["library"][]="kidiklik_admin/kidiklik_admin.commands";
		/* on va récupérer la liste des clients du département concerné */
		$clients=\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"client","field_departement"=>$term_dep]);
		/* vérification si un adhérent doit être lié à un client */
		if(\Drupal::routeMatch()->getParameters()->get("node"))
			$nid=(int)\Drupal::routeMatch()->getParameters()->get("node")->id();
		$entity_id=""; /* entité cliente */
		if($nid) {
			$database = \Drupal::database();
			$query=$database->query("select * from {node__field_adherent} where field_adherent_target_id = '".$nid."'");
			/* un adhérent est lié à un seul client, on peut récupérer le premier élément courant */
			$result=current($query->fetchAll());
			$entity_id=$result->entity_id;
		}
		$tab=[];
		$tab[""]="Veuillez choisir un client";
		foreach($clients as $key=>$client) {
			$tab[$key]=$client->getTitle();
		}
		$form["field_client"]["widget"]["#options"]=$tab;
		if($entity_id && !count($form["field_client"]["widget"]["#default_value"]))
			$form["field_client"]["widget"]["#default_value"][]=(string)$entity_id;
			
		$form["field_code_postal"]["widget"][0]["value"]["#ajax"]=[
			"callback"=>"getAjaxVille",
			"disable-refocus" => TRUE,
			"event" => "blur",
			
			"wrapper" =>"edit-field-ville-wrapper",
			
			"progress"=>[
				"type"=>"throbber",
				"message"=>NULL,
			],

		];
		if($form["field_ville"]["widget"]["#default_value"]) {
			foreach($form["field_ville"]["widget"]["#options"] as $key=>&$item) {
				
				
				if($key!=(int)current($form["field_ville"]["widget"]["#default_value"])) unset($form["field_ville"]["widget"]["#options"][$key]);
			}
			
		}//else $form["field_ville"]["widget"]["#options"]=[];
	//	kint($form["field_ville"]);

	}
	
	if($form_id=="node_client_edit_form" || $form_id=="node_client_form") {
		$form["#attached"]["library"][]="kidiklik_admin/kidiklik_admin.commands";
		/* on met en place la fonctionnalité AJAX */
		$form["field_code_postal"]["widget"][0]["value"]["#ajax"]=[
			"callback"=>"getAjaxVille",
			"disable-refocus" => TRUE,
			"event" => "blur",
			
			"wrapper" =>"edit-field-ville-wrapper",
			
			"progress"=>[
				"type"=>"throbber",
				"message"=>NULL,
			],

		];
		if($form["field_ville"]["widget"]["#default_value"]) {
			foreach($form["field_ville"]["widget"]["#options"] as $key=>&$item) {
				
				
				if($key!=(int)current($form["field_ville"]["widget"]["#default_value"])) unset($form["field_ville"]["widget"]["#options"][$key]);
			}
			
		}else $form["field_ville"]["widget"]["#options"]=[];

	}


}

function kidiklik_admin_form_submit(&$form, FormStateInterface $form_state) {
	//$form["field_activite"]["widget"]["#options"]=$form["save_activite"];
	//kint($form_state);kint($form);	kint($form["field_activite"]);exit;
	$form["field_activite"]["#needs_validation"]=false;
	$form["field_activite"]["widget"]["#needs_validation"]=false;
	$form["field_activite"]["widget"]["#limit_validation_errors"]=[];
	$form["field_activite"]["#validated"]=true;
	
}

function kidiklik_admin_form_validate($form, FormStateInterface $form_state) {
	
	//kint($form["field_activite"]);
}

function getAjaxVille(array &$form, FormStateInterface $form_state) {
	$cp=current($form_state->getValue("field_code_postal"));
	/* je cherche le term possédant le code postal saisi */
	$query=\Drupal::entityQuery('taxonomy_term');
	$query->condition("field_code_postal",$cp); 
	//$ville_id=$query->execute();
	//return $form["field_code_postal"];
	/* on charge tous les termes correspondant à la ville */
	$villes=Term::loadMultiple($query->execute());//current(\Drupal::entityTypeManager()->getStorage("taxonomy_term")->loadByProperties(["vid"=>"ville","tid"=>$ville_id]));
	$tab=array();
	
	/* on construit un tableau qui va être envoyé en json à JS */
	foreach($villes as $ville) {
		$tab[]=["key"=>$ville->id(),"val"=>$ville->getName()];
	}
	$form["field_ville"]["widget"]["#options"]=$tab;
	//return $form["field_ville"];
	$response = new AjaxResponse();
	//kint_require();
	
	 //$output = @Kint::dump($tab);
	// $response->addCommand(new ReplaceCommand("#edit-field-ville-wrapper", $output ));
	$response->addCommand(new InvokeCommand(NULL,"getAjaxVille", [$tab] ));
	return $response;
}

function getAjaxCoordonnees(array &$form, FormStateInterface $form_state) {

	/*if($adherent=$form_state->getValue("field_adherent")) {
		$selectedText = $form['field_adherent']['#options'][$adherent];
      $form['output']['#value'] = $selectedText;
	}*/
	
	//return ['#markup' => $adherent];
	
	$response = new AjaxResponse();
	$select_id=current($form_state->getValue("field_adherent"));
	$adherent=current(\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"adherent","nid"=>$select_id]));
	/* recherche des activites en fonction de l'adhérent */ 
	$activites=\Drupal::entityTypeManager()->getStorage("node")->loadByProperties(["type"=>"activite","field_adherent"=>$select_id]);
	if(is_object($adherent)) {
		
		/* cette methode fonctionne mais ne semble pas permettre de choisir plus d'une sélection */ 
		$form["field_adresse"]["widget"][0]["value"]["#value"]=current($adherent->get("field_adresse")->getValue());
		$form["field_code_postal"]["widget"][0]["value"]["#value"]=current($adherent->get("field_code_postal")->getValue());
		$form["field_telephone"]["widget"][0]["value"]["#value"]=current($adherent->get("field_telephone")->getValue())["value"];
		$form["field_email"]["widget"][0]["value"]["#value"]=current($adherent->get("field_email")->getValue());
		$form["field_lien"]["widget"][0]["value"]["#value"]=current($adherent->get("field_lien")->getValue());
		$tab[]="Veuillez choisir une activité";
		foreach($activites as $activite) {
			
			$tab[$activite->id()]=$activite->getTitle();
		}
		$form["field_activite"]["widget"]["#options"]=$tab;
		//$form["field_ville"]["widget"][0]["value"]["#value"]=$ville->id();
		//$form["coordonnee"][]=$form["field_adherent"];
		$form["coordonnee"]=[
			"#type"=>"div",
			"#prefix"=>"<div id='coordonnees-adherent'>",
		];
		$form["coordonnee"][]=$form["field_adresse"];
		$form["coordonnee"][]=$form["field_code_postal"];
		$form["coordonnee"][]=$form["field_telephone"];
		$form["coordonnee"][]=$form["field_email"];
		$form["coordonnee"][]=$form["field_lien"];
		$form["coordonnee"][]=$form["field_lieu"];
		$form["coordonnee"][]=$form["field_activite"];
		
		
		$renderer= \Drupal::service("renderer");
		$renderedField=$renderer->render($form["coordonnee"]);
		
		$response->addCommand(new ReplaceCommand('#coordonnees-adherent', $renderedField));
		return $response; 
		//$form["coordonnee"][]=$form["field_ville"];
		return $form["coordonnee"];
		
		/* methode avec un appel JS */
		$ville=current(\Drupal::entityTypeManager()->getStorage("taxonomy_term")->loadByProperties(["vid"=>"ville","tid"=>current($adherent->get("field_ville")->getValue())["target_id"]]));
		$test["adresse"]=current($adherent->get("field_adresse")->getValue());
		$test["code_postal"]=current($adherent->get("field_code_postal")->getValue());
		$test["telephone"]=current($adherent->get("field_telephone")->getValue());
		$test["email"]=current($adherent->get("field_email")->getValue());
		$test["ville"]=["id"=>$ville->id(),"name"=>$ville->getName()];//["id"=>current($adherent->get("field_ville")->getValue());
		$test["lien"]=current($adherent->get("field_lien")->getValue());
		
		/* on boucle */
		foreach($activites as $activite) {
			$test["activites"][]=["id"=>$activite->id(),"name"=>$activite->getTitle()];
		}
		
	}
	//return [];
	
//	kint_require();

	// $debugOut = @Kint::dump($test);	
	//kint($test);
	$response->addCommand(new InvokeCommand(NULL, 'getAjaxCoordonnees', [$test]));
	return $response;
}