# Schema for the limit_domain_access_by_role module settings.

limit_domain_access_by_role.settings:
  type: config_object
  label: 'Limit Domain Access By Role settings'
  mapping:
    technical_domains:
      type: string
      label: "Technical domains"
