# Schema for the configuration files of the Mailjet Subscription module.


mailjet_subscription.mailjet_subscription_form.*:
  type: config_entity
  label: 'Mailjet Subscription config'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: text
      label: 'Name'
      translatable: true
    uuid:
      type: string
      label: 'UUID'
    description:
      type: string
      label: 'Description'
      translatable: true
    sumbit_label:
      type: string
      label: 'Sumbit Label'
      translatable: true
    destination_page:
      type: string
      label: 'Destination page'
    error_token:
      type: string
      label: 'Error Token'
      translatable: true
    confirmation_email_text:
      type: string
      label: 'Confirmation email text'
      translatable: true
    email_text_button:
      type: string
      label: 'Email text button'
      translatable: true
    email_text_description:
      type: string
      label: 'Email description'
      translatable: true
    email_text_thank_you:
      type: string
      label: 'Email text thank you'
      translatable: true
    email_owner:
      type: string
      label: 'Email Owner'
    contact_exist:
      type: string
      label: 'Contact exist message'
      translatable: true
    lists:
      type: string
      label: 'Lists'
    fields_mailjet:
      type: string
      label: 'Contact properties'
      translatable: true
    css_field:
      type: string
      label: 'CSS FIELD'
    js_field:
      type: string
      label: 'JS field'
    email_footer_text:
      type: string
      label: 'Email Footer text'
      translatable: true
    error_data_types:
      type: string
      label: 'Data type error message'
      translatable: true
    confirmation_message:
      type: string
      label: 'Confirmation message'
      translatable: true
    subscribe_error:
      type: string
      label: 'Subscribe error'
      translatable: true
    success_message_subsribe:
      type: string
      label: 'Success message'
      translatable: true
    created_date:
      type: string
      label: 'Created time'
      translatable: true
    changed_date:
      type: string
      label: 'Changed time'
      translatable: true
    email_label:
      type: string
      label: 'Email Label'
      translatable: true
    labels_fields:
      type: string
      label: 'Signup form properties ( labels )'
      translatable: true
    sort_fields:
      type: string
      label: 'Sort configuration for contact properties'
      translatable: true
